### ISSUE TITLE
我抓包下来请求体加密了

### ISSUE THREAD

**Issue by 1234zhang** [ourongxing/CQUPT-Health-ClockIn#2]
我今天晚上抓包下来，发现请求体不是base64的，是加密代码。。

**Comment by 468336329Zc** [comment]
哪个请求?不都是base64加密? 不过倒是打卡的这个api请求字段mrdkkey博主是怎么想到是date+hour得到的字符串。

**Comment by ourongxing** [comment]
> 哪个请求?不都是base64加密? 不过倒是打卡的这个api请求字段mrdkkey博主是怎么想到是date+hour得到的字符串。

#1

**Comment by ourongxing** [comment]
我刚才重新抓了一下，key 依旧是 base64 加密，你可能哪里搞错了。另外提示一下，进入资讯页面就可以获得明文的 openid。
