### ISSUE TITLE
打卡失败

### ISSUE THREAD

**Issue by 468336329Zc** [ourongxing/CQUPT-Health-ClockIn#3]
运行结果：
1.检测重复打卡-今日首次打卡
2.获取学生信息成功
3.获取地址成功
4.打卡失败，重新打卡
5.发送信息成功

原因分析：
打卡失败，看了代码状态码不是200，就失败。
难道自动打卡的api有问题吗？没能打卡成功？

**Comment by 468336329Zc** [comment]
确定openid正确。

**Comment by ourongxing** [comment]
好像是有一定概率会失败，一般重试就行，现在我改为了每天打卡两次

**Comment by 468336329Zc** [comment]
> 好像是有一定概率会失败，一般重试就行，现在我改为了每天打卡两次

我postman测试了一下，就没成功发送过，收到都是403 已过期。实在没想懂，它应该就是使用mrdkkey做验证的把。

**Comment by ourongxing** [comment]
> 我postman测试了一下，就没成功发送过，收到都是403 已过期。实在没想懂，它应该就是使用mrdkkey做验证

通过 openid 和时间戳验证，时间戳会过期，mrdkkey 不需要也能打卡成功

**Comment by 1234zhang** [comment]
我也是一直遇到403已过期。没有打卡成功过
