### ISSUE TITLE
本地打卡失败 获取地址失败

### ISSUE THREAD

**Issue by Gabriel-18** [ourongxing/CQUPT-Health-ClockIn#7]
![image](https://user-images.githubusercontent.com/38080169/105381350-dfada800-5c49-11eb-96e1-1f8e7237016d.png)

**Comment by 468336329Zc** [comment]
这个是用的qq的接口，地址获取不到嘛，通常是超时网络不好，或者地址确实一些偏僻造成。为了防止打卡失败，所以多搞几个定时执行即可。

**Comment by Gabriel-18** [comment]
> 这个是用的qq的接口，地址获取不到嘛，通常是超时网络不好，或者地址确实一些偏僻造成。为了防止打卡失败，所以多搞几个定时执行即可。

我之前写的地址是重邮，后面改成了重庆邮电大学就打卡成功了

**Comment by ourongxing** [comment]
> > 这个是用的qq的接口，地址获取不到嘛，通常是超时网络不好，或者地址确实一些偏僻造成。为了防止打卡失败，所以多搞几个定时执行即可。
> 
> 我之前写的地址是重邮，后面改成了重庆邮电大学就打卡成功了

请严格按照 区/县 + 小区/街道/村 + 门牌号 填写详细地址
