### ISSUE TITLE
本地打卡失败 

### ISSUE THREAD

**Issue by Cansiny0320** [ourongxing/CQUPT-Health-ClockIn#8]
![image](https://user-images.githubusercontent.com/51797219/105520865-20053880-5cd3-11eb-860e-c5a06990cd55.png)

**Comment by Cansiny0320** [comment]
返回status  400

**Comment by ourongxing** [comment]
抱歉，最近更新了一个 bug 出来，马上修复

**Comment by ourongxing** [comment]
修复了，是坐标参数的类型搞错了。话说你们红岩的获取学生信息的接口怎么1点钟就关了。

**Comment by Cansiny0320** [comment]
![Uploading image.png…]()
你可以在本地打卡成功吗

**Comment by Cansiny0320** [comment]
> 修复了，是坐标参数的类型搞错了。话说你们红岩的获取学生信息的接口怎么1点钟就关了。

![image](https://user-images.githubusercontent.com/51797219/105607089-c6654280-5d94-11eb-92c8-ff44d39fb66c.png)
你可以在本地打卡成功吗

**Comment by ourongxing** [comment]
> > 修复了，是坐标参数的类型搞错了。话说你们红岩的获取学生信息的接口怎么1点钟就关了。
> 
> ![image](https://user-images.githubusercontent.com/51797219/105607089-c6654280-5d94-11eb-92c8-ff44d39fb66c.png)
> 你可以在本地打卡成功吗

你应该是 openid 错了

**Comment by Cansiny0320** [comment]
> > > 修复了，是坐标参数的类型搞错了。话说你们红岩的获取学生信息的接口怎么1点钟就关了。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/51797219/105607089-c6654280-5d94-11eb-92c8-ff44d39fb66c.png)
> > 你可以在本地打卡成功吗
> 
> 你应该是 openid 错了
确实是这样 解决了

**Comment by ourongxing** [comment]
其实昨天就是你的 openid 错了，那个 bug 其实不影响打卡。
